'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { instrumentSerif } from '@/lib/fonts';

const wordAnim = {
    hidden: { opacity: 0, y: 20, filter: 'blur(8px)' },
    visible: {
        opacity: 1,
        y: 0,
        filter: 'blur(0px)',
        transition: { duration: 0.6, ease: [0.25, 0.1, 0.25, 1] as const },
    },
};

const container = {
    hidden: {},
    visible: {
        transition: {
            staggerChildren: 0.08,
        },
    },
};

export default function TermsPage() {
    return (
        <main className="min-h-screen relative overflow-hidden bg-white">
            {/* Background Image */}
            <div
                className="absolute inset-0 z-0 bg-cover bg-center bg-no-repeat pointer-events-none opacity-40"
                style={{ backgroundImage: 'url("/event_bg.png")' }}
            />

            <div className="relative z-10 pt-[120px] pb-24 px-4 md:px-12 lg:px-16">
                {/* Hero Section */}
                <section className="mb-20">
                    <div className="max-w-4xl">
                        <motion.h1
                            className={`${instrumentSerif.className} text-[#1a1a1a] text-[12vw] md:text-[7.5vw] lg:text-[7vw] xl:text-[5.5vw] leading-[1] md:leading-[0.95] tracking-[-0.02em]`}
                            variants={container}
                            initial="hidden"
                            whileInView="visible"
                            viewport={{ once: true }}
                        >
                            <div className="block">
                                {['Terms', 'and', 'Conditions'].map((word, i) => (
                                    <motion.span
                                        key={`title-${i}`}
                                        variants={wordAnim}
                                        className="inline-block mr-[0.3em]"
                                    >
                                        {word}
                                    </motion.span>
                                ))}
                            </div>
                        </motion.h1>
                        <p className="mt-8 text-[#1a1a1a]/60 text-lg md:text-xl max-w-2xl font-light">
                            Last Updated: February 12, 2026
                        </p>
                    </div>
                </section>

                {/* Content Section */}
                <div className="max-w-4xl mx-auto md:mx-0 space-y-12 text-[#1a1a1a]">

                    {/* Intro */}
                    <section className="space-y-4 text-lg font-light leading-relaxed text-[#1a1a1a]/80">
                        <p>
                            This document is an electronic record in terms of the Information Technology Act, 2000 and rules made thereunder, including applicable amended provisions pertaining to electronic records in various statutes as amended from time to time. This electronic record is generated by a computer system and does not require any physical or digital signature.
                        </p>
                        <p>
                            This document is published in accordance with applicable law requiring publication of rules and regulations, privacy policy, and terms for access or usage of this website and related platform services (collectively, the &quot;Platform&quot;).
                        </p>
                        <p>
                            The Platform is owned and operated by Akar Women Group (hereinafter referred to as the &quot;Platform Owner&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;). These Terms and Conditions (&quot;Terms&quot;) govern your use of the Platform and all related goods/services, including workshops, masterclasses, events, educational content, consultations, memberships, and related offerings (collectively, &quot;Services&quot;).
                        </p>
                        <p>
                            By accessing, browsing, registering, or otherwise using the Platform, you agree to be bound by these Terms, the Privacy Policy, the Refund and Cancellation Policy, and other policies published on the Platform. If you do not agree, do not access or use the Platform.
                        </p>
                    </section>

                    {/* 1. User Eligibility and Acceptance */}
                    <section className="space-y-4">
                        <h2 className={`${instrumentSerif.className} text-3xl md:text-4xl mb-6`}>1. User Eligibility and Acceptance</h2>
                        <div className="space-y-4 text-lg font-light leading-relaxed text-[#1a1a1a]/80">
                            <p>
                                For the purpose of these Terms, &quot;you&quot;, &quot;your&quot;, or &quot;user&quot; means any natural or legal person who accesses or uses the Platform. If you are using the Platform on behalf of an entity, you represent that you are authorized to bind that entity to these Terms.
                            </p>
                            <p className="font-medium uppercase tracking-wide text-[#1a1a1a]">
                                ACCESSING, BROWSING, REGISTERING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR ACCEPTANCE OF ALL TERMS, CONDITIONS, POLICIES, DISCLAIMERS, AND NOTICES REFERENCED HEREIN.
                            </p>
                        </div>
                    </section>

                    {/* 2. Account Registration and Information Accuracy */}
                    <section className="space-y-4">
                        <h2 className={`${instrumentSerif.className} text-3xl md:text-4xl mb-6`}>2. Account Registration and Information Accuracy</h2>
                        <div className="space-y-4 text-lg font-light leading-relaxed text-[#1a1a1a]/80">
                            <p>
                                To access certain Services, you may be required to register and provide information. You agree to provide true, accurate, complete, and current information and to update it promptly when required. You are responsible for all activities conducted through your account credentials.
                            </p>
                            <p>
                                We reserve the right to suspend or terminate access where information appears false, incomplete, misleading, fraudulent, or in violation of law or these Terms.
                            </p>
                        </div>
                    </section>

                    {/* 3. Service Scope and Platform Nature */}
                    <section className="space-y-4">
                        <h2 className={`${instrumentSerif.className} text-3xl md:text-4xl mb-6`}>3. Service Scope and Platform Nature</h2>
                        <div className="space-y-4 text-lg font-light leading-relaxed text-[#1a1a1a]/80">
                            <p>
                                Akar Women Group provides educational and professional growth-oriented offerings. Services may include digital or physical sessions, hybrid events, recorded modules, downloadable resources, mentorship interactions, and community access, depending on the specific program purchased.
                            </p>
                            <p>
                                We may modify, update, discontinue, or restructure any Service element, schedule, speaker lineup, curriculum component, or delivery format at our discretion due to operational, legal, safety, partner, or force majeure reasons.
                            </p>
                        </div>
                    </section>

                    {/* 4. Payments, Pricing, and Billing */}
                    <section className="space-y-4">
                        <h2 className={`${instrumentSerif.className} text-3xl md:text-4xl mb-6`}>4. Payments, Pricing, and Billing</h2>
                        <div className="space-y-4 text-lg font-light leading-relaxed text-[#1a1a1a]/80">
                            <p>
                                You agree to pay all fees and charges associated with Services selected by you. Prices, taxes, statutory levies, and convenience charges (if any) are payable as displayed at checkout unless otherwise specified.
                            </p>
                            <p>
                                Payment processing may be handled through third-party payment gateways. By transacting on the Platform, you authorize us and our payment partners to process your payment information as required for transaction completion and compliance.
                            </p>
                            <p>
                                Your transaction constitutes a legally binding and enforceable contract for the selected Services.
                            </p>
                        </div>
                    </section>

                    {/* 5. Refund and Cancellation Linkage */}
                    <section className="space-y-4">
                        <h2 className={`${instrumentSerif.className} text-3xl md:text-4xl mb-6`}>5. Refund and Cancellation Linkage</h2>
                        <div className="space-y-4 text-lg font-light leading-relaxed text-[#1a1a1a]/80">
                            <p>
                                All purchases are governed by the separately published Refund and Cancellation Policy. By making payment on the Platform, you expressly agree to those terms, including the applicable No Refund and No Cancellation conditions where stated.
                            </p>
                        </div>
                    </section>

                    {/* 6. No Warranty and Limitation of Reliance */}
                    <section className="space-y-4">
                        <h2 className={`${instrumentSerif.className} text-3xl md:text-4xl mb-6`}>6. No Warranty and Limitation of Reliance</h2>
                        <div className="space-y-4 text-lg font-light leading-relaxed text-[#1a1a1a]/80">
                            <p>
                                Information, materials, and Services on the Platform are provided on an &quot;as is&quot; and &quot;as available&quot; basis. Neither we nor any third party makes any warranty or representation regarding accuracy, timeliness, suitability, completeness, reliability, or performance for any specific purpose, to the fullest extent permitted by applicable law.
                            </p>
                            <p>
                                You acknowledge that platform content may contain typographical errors, inadvertent inaccuracies, or updates made over time, and you agree to independently assess suitability of Services for your objectives.
                            </p>
                        </div>
                    </section>

                    {/* 7. User Responsibilities and Prohibited Conduct */}
                    <section className="space-y-4">
                        <h2 className={`${instrumentSerif.className} text-3xl md:text-4xl mb-6`}>7. User Responsibilities and Prohibited Conduct</h2>
                        <div className="space-y-4 text-lg font-light leading-relaxed text-[#1a1a1a]/80">
                            <p>You agree not to:</p>
                            <ul className="list-disc pl-5 space-y-2">
                                <li>use the Platform for any unlawful, fraudulent, abusive, or prohibited purpose;</li>
                                <li>misrepresent identity or provide inaccurate registration/payment details;</li>
                                <li>attempt unauthorized access, reverse engineering, scraping, or interference with platform security;</li>
                                <li>upload or transmit malicious code, spam, or harmful content;</li>
                                <li>copy, reproduce, redistribute, or commercially exploit proprietary content without prior written permission.</li>
                            </ul>
                        </div>
                    </section>

                    {/* 8. Intellectual Property Rights */}
                    <section className="space-y-4">
                        <h2 className={`${instrumentSerif.className} text-3xl md:text-4xl mb-6`}>8. Intellectual Property Rights</h2>
                        <div className="space-y-4 text-lg font-light leading-relaxed text-[#1a1a1a]/80">
                            <p>
                                All Platform content, including but not limited to design, layout, logos, branding, text, graphics, audio/video material, and curriculum resources, is proprietary to or licensed by Akar Women Group and protected under applicable intellectual property laws.
                            </p>
                            <p>
                                Except as expressly permitted in writing, no right, title, or interest in any intellectual property is transferred to you by virtue of using the Platform.
                            </p>
                        </div>
                    </section>

                    {/* 9. Third-Party Links and Services */}
                    <section className="space-y-4">
                        <h2 className={`${instrumentSerif.className} text-3xl md:text-4xl mb-6`}>9. Third-Party Links and Services</h2>
                        <div className="space-y-4 text-lg font-light leading-relaxed text-[#1a1a1a]/80">
                            <p>
                                The Platform may contain links to third-party websites or services for convenience. Access to such links is at your own discretion and subject to third-party terms and privacy practices. We are not responsible for third-party content, policies, service levels, or actions.
                            </p>
                        </div>
                    </section>

                    {/* 10. Indemnity */}
                    <section className="space-y-4">
                        <h2 className={`${instrumentSerif.className} text-3xl md:text-4xl mb-6`}>10. Indemnity</h2>
                        <div className="space-y-4 text-lg font-light leading-relaxed text-[#1a1a1a]/80">
                            <p>
                                You agree to indemnify, defend, and hold harmless Akar Women Group, its affiliates, officers, directors, employees, representatives, and partners from and against any claims, liabilities, losses, damages, penalties, costs, and expenses (including reasonable legal fees) arising out of or related to: (a) your breach of these Terms or applicable policies; (b) your violation of applicable law; or (c) your infringement of any rights of a third party.
                            </p>
                        </div>
                    </section>

                    {/* 11. Limitation of Liability */}
                    <section className="space-y-4">
                        <h2 className={`${instrumentSerif.className} text-3xl md:text-4xl mb-6`}>11. Limitation of Liability</h2>
                        <div className="space-y-4 text-lg font-light leading-relaxed text-[#1a1a1a]/80">
                            <p>
                                To the maximum extent permitted by law, Akar Women Group shall not be liable for any indirect, incidental, special, consequential, punitive, or exemplary damages, including loss of data, income, goodwill, opportunity, or business interruption arising from use of or inability to use the Platform.
                            </p>
                            <p>
                                In any event, our aggregate liability in relation to any claim shall not exceed the amount actually paid by you for the specific Service giving rise to such claim, unless otherwise mandated under applicable law.
                            </p>
                        </div>
                    </section>

                    {/* 12. Force Majeure */}
                    <section className="space-y-4">
                        <h2 className={`${instrumentSerif.className} text-3xl md:text-4xl mb-6`}>12. Force Majeure</h2>
                        <div className="space-y-4 text-lg font-light leading-relaxed text-[#1a1a1a]/80">
                            <p>
                                Neither party shall be liable for failure or delay in performance caused by events beyond reasonable control, including natural disasters, pandemic, internet/network outages, government actions, labor disputes, war, civil disturbances, or partner/vendor failures.
                            </p>
                        </div>
                    </section>

                    {/* 13. Suspension and Termination */}
                    <section className="space-y-4">
                        <h2 className={`${instrumentSerif.className} text-3xl md:text-4xl mb-6`}>13. Suspension and Termination</h2>
                        <div className="space-y-4 text-lg font-light leading-relaxed text-[#1a1a1a]/80">
                            <p>
                                We may suspend, restrict, or terminate access to the Platform or Services at our discretion, with or without prior notice, where required for security, legal compliance, suspected fraud, policy breach, or operational continuity.
                            </p>
                        </div>
                    </section>

                    {/* 14. Modification of Terms */}
                    <section className="space-y-4">
                        <h2 className={`${instrumentSerif.className} text-3xl md:text-4xl mb-6`}>14. Modification of Terms</h2>
                        <div className="space-y-4 text-lg font-light leading-relaxed text-[#1a1a1a]/80">
                            <p>
                                We reserve the right to modify these Terms at any time. Updated Terms will be posted on the Platform with a revised effective date. Continued use of the Platform after such update constitutes your acceptance of the revised Terms.
                            </p>
                        </div>
                    </section>

                    {/* 15. Governing Law and Jurisdiction */}
                    <section className="space-y-4">
                        <h2 className={`${instrumentSerif.className} text-3xl md:text-4xl mb-6`}>15. Governing Law and Jurisdiction</h2>
                        <div className="space-y-4 text-lg font-light leading-relaxed text-[#1a1a1a]/80">
                            <p>
                                These Terms and any dispute or claim arising out of or in connection with them shall be governed by and construed in accordance with the laws of India. Subject to applicable law, courts located in Mumbai, Maharashtra shall have exclusive jurisdiction over all disputes.
                            </p>
                        </div>
                    </section>

                    {/* 16. Communications */}
                    <section className="space-y-4">
                        <h2 className={`${instrumentSerif.className} text-3xl md:text-4xl mb-6`}>16. Communications</h2>
                        <div className="space-y-4 text-lg font-light leading-relaxed text-[#1a1a1a]/80">
                            <p>
                                All concerns or communications relating to these Terms, Services, billing, or platform usage must be made through the official contact channels provided on this Platform.
                            </p>
                        </div>
                    </section>

                </div>
            </div>
        </main>
    );
}
